// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC893vSt0U0AliKgYQ30oEdqz4RNaE7UMg',
    appId: '1:703306803714:web:88bafe18439c982a45151b',
    messagingSenderId: '703306803714',
    projectId: 'github-cba6a',
    authDomain: 'github-cba6a.firebaseapp.com',
    storageBucket: 'github-cba6a.appspot.com',
    measurementId: 'G-6ZQTWEBJ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlbQzfGmtPMbwIu_pUnv3obv8VWPM09Q',
    appId: '1:703306803714:android:1a6cad863c56c55745151b',
    messagingSenderId: '703306803714',
    projectId: 'github-cba6a',
    storageBucket: 'github-cba6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiEM1U05YJ288Olcpj8OKOrDviml8gTBg',
    appId: '1:703306803714:ios:9a13028f6bf6456445151b',
    messagingSenderId: '703306803714',
    projectId: 'github-cba6a',
    storageBucket: 'github-cba6a.appspot.com',
    iosBundleId: 'com.example.gitprogect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiEM1U05YJ288Olcpj8OKOrDviml8gTBg',
    appId: '1:703306803714:ios:ac36aeeb7045a42145151b',
    messagingSenderId: '703306803714',
    projectId: 'github-cba6a',
    storageBucket: 'github-cba6a.appspot.com',
    iosBundleId: 'com.example.gitprogect.RunnerTests',
  );
}
